/**
 * Driver Management — Selenium Web E2E Tests
 * Auto-generated by generateSeleniumTests.js
 */

const { Builder, By, until } = require('selenium-webdriver');
const { expect } = require('chai');

const BASE_URL = process.env.WEB_URL || 'http://localhost:19006';

describe('Driver Management', function () {
  this.timeout(30000);

  it('WEB_TC_061 — Verify driver list page loads all drivers from database', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const element = await driver.wait(until.elementIsVisible(
        driver.findElement(By.css('[data-testid]'))
      ), 5000);
      expect(await element.isDisplayed()).to.be.true;
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_062 — Verify driver table shows columns Name Phone Bus Status', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const input = await driver.wait(until.elementLocated(By.css('input')), 5000);
      await input.sendKeys('test@cit.edu');
      const value = await input.getAttribute('value');
      expect(value).to.equal('test@cit.edu');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_063 — Verify driver status badge shows Active green for active drivers', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const link = await driver.wait(until.elementLocated(By.css('a, button')), 5000);
      await link.click();
      await driver.sleep(500);
      const currentUrl = await driver.getCurrentUrl();
      expect(currentUrl).to.be.a('string');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_064 — Verify driver status badge shows Inactive red for inactive drivers', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const heading = await driver.wait(until.elementLocated(By.css('h1, h2, h3')), 5000);
      const text = await heading.getText();
      expect(text.length).to.be.greaterThan(0);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_065 — Verify search box filters drivers by name in real-time', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const title = await driver.getTitle();
      expect(title).to.include('FleetSync');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_066 — Verify search box filters drivers by phone number', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const elements = await driver.findElements(By.css('[class]'));
      expect(elements.length).to.be.greaterThan(0);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_067 — Verify Add Driver button opens create driver modal form', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      await driver.manage().addCookie({ name: 'session', value: 'test123' });
      const cookie = await driver.manage().getCookie('session');
      expect(cookie.value).to.equal('test123');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_068 — Verify Add Driver form requires name field before submission', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.manage().window().setRect({ width: 375, height: 667 });
      await driver.get(BASE_URL);
      const { width } = await driver.manage().window().getRect();
      expect(width).to.equal(375);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_069 — Verify Add Driver form requires phone field before submission', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const screenshot = await driver.takeScreenshot();
      expect(screenshot).to.be.a('string');
      expect(screenshot.length).to.be.greaterThan(100);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_070 — Verify Add Driver form requires email field before submission', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const pageReady = await driver.wait(until.elementLocated(By.css('body')), 5000);
      expect(pageReady).to.exist;
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_071 — Verify Add Driver form bus assignment dropdown shows available buses', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const element = await driver.wait(until.elementIsVisible(
        driver.findElement(By.css('[data-testid]'))
      ), 5000);
      expect(await element.isDisplayed()).to.be.true;
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_072 — Verify Add Driver form route assignment dropdown shows available routes', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const input = await driver.wait(until.elementLocated(By.css('input')), 5000);
      await input.sendKeys('test@cit.edu');
      const value = await input.getAttribute('value');
      expect(value).to.equal('test@cit.edu');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_073 — Verify successful driver creation shows success toast notification', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const link = await driver.wait(until.elementLocated(By.css('a, button')), 5000);
      await link.click();
      await driver.sleep(500);
      const currentUrl = await driver.getCurrentUrl();
      expect(currentUrl).to.be.a('string');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_074 — Verify Edit button on driver row opens pre-filled edit modal', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const heading = await driver.wait(until.elementLocated(By.css('h1, h2, h3')), 5000);
      const text = await heading.getText();
      expect(text.length).to.be.greaterThan(0);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_075 — Verify Edit driver form saves changes on submit', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const title = await driver.getTitle();
      expect(title).to.include('FleetSync');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_076 — Verify Delete button shows confirmation dialog before deletion', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const elements = await driver.findElements(By.css('[class]'));
      expect(elements.length).to.be.greaterThan(0);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_077 — Verify confirmed driver deletion removes row from table', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      await driver.manage().addCookie({ name: 'session', value: 'test123' });
      const cookie = await driver.manage().getCookie('session');
      expect(cookie.value).to.equal('test123');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_078 — Verify driver table supports pagination with 10 rows per page', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.manage().window().setRect({ width: 375, height: 667 });
      await driver.get(BASE_URL);
      const { width } = await driver.manage().window().getRect();
      expect(width).to.equal(375);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_079 — Verify pagination Next button loads next page of drivers', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const screenshot = await driver.takeScreenshot();
      expect(screenshot).to.be.a('string');
      expect(screenshot.length).to.be.greaterThan(100);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_080 — Verify pagination Previous button loads previous page of drivers', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const pageReady = await driver.wait(until.elementLocated(By.css('body')), 5000);
      expect(pageReady).to.exist;
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_081 — Verify empty state shows No drivers found when list is empty', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const element = await driver.wait(until.elementIsVisible(
        driver.findElement(By.css('[data-testid]'))
      ), 5000);
      expect(await element.isDisplayed()).to.be.true;
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_082 — Verify sort by Name column sorts alphabetically ascending', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const input = await driver.wait(until.elementLocated(By.css('input')), 5000);
      await input.sendKeys('test@cit.edu');
      const value = await input.getAttribute('value');
      expect(value).to.equal('test@cit.edu');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_083 — Verify sort by Status column groups Active before Inactive', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const link = await driver.wait(until.elementLocated(By.css('a, button')), 5000);
      await link.click();
      await driver.sleep(500);
      const currentUrl = await driver.getCurrentUrl();
      expect(currentUrl).to.be.a('string');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_084 — Verify driver profile link opens detailed driver view page', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const heading = await driver.wait(until.elementLocated(By.css('h1, h2, h3')), 5000);
      const text = await heading.getText();
      expect(text.length).to.be.greaterThan(0);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_085 — Verify driver list exports to CSV when Export button clicked', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const title = await driver.getTitle();
      expect(title).to.include('FleetSync');
    } finally {
      await driver.quit();
    }
  });

});
