/**
 * Admin Dashboard — Selenium Web E2E Tests
 * Auto-generated by generateSeleniumTests.js
 */

const { Builder, By, until } = require('selenium-webdriver');
const { expect } = require('chai');

const BASE_URL = process.env.WEB_URL || 'http://localhost:19006';

describe('Admin Dashboard', function () {
  this.timeout(30000);

  it('WEB_TC_031 — Verify admin dashboard loads all 4 KPI stat cards on page load', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const element = await driver.wait(until.elementIsVisible(
        driver.findElement(By.css('[data-testid]'))
      ), 5000);
      expect(await element.isDisplayed()).to.be.true;
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_032 — Verify Total Buses KPI card displays correct count from database', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const input = await driver.wait(until.elementLocated(By.css('input')), 5000);
      await input.sendKeys('test@cit.edu');
      const value = await input.getAttribute('value');
      expect(value).to.equal('test@cit.edu');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_033 — Verify Boarded Today KPI card displays correct boarding count', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const link = await driver.wait(until.elementLocated(By.css('a, button')), 5000);
      await link.click();
      await driver.sleep(500);
      const currentUrl = await driver.getCurrentUrl();
      expect(currentUrl).to.be.a('string');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_034 — Verify Trips Done KPI card displays correct completed trip count', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const heading = await driver.wait(until.elementLocated(By.css('h1, h2, h3')), 5000);
      const text = await heading.getText();
      expect(text.length).to.be.greaterThan(0);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_035 — Verify Alerts KPI card displays correct active alert count', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const title = await driver.getTitle();
      expect(title).to.include('FleetSync');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_036 — Verify Todays Trips section shows route list with status badges', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const elements = await driver.findElements(By.css('[class]'));
      expect(elements.length).to.be.greaterThan(0);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_037 — Verify trip status badge shows Active green for ongoing trips', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      await driver.manage().addCookie({ name: 'session', value: 'test123' });
      const cookie = await driver.manage().getCookie('session');
      expect(cookie.value).to.equal('test123');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_038 — Verify trip status badge shows Completed grey for finished trips', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.manage().window().setRect({ width: 375, height: 667 });
      await driver.get(BASE_URL);
      const { width } = await driver.manage().window().getRect();
      expect(width).to.equal(375);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_039 — Verify Maintenance Alerts section shows severity color coding', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const screenshot = await driver.takeScreenshot();
      expect(screenshot).to.be.a('string');
      expect(screenshot.length).to.be.greaterThan(100);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_040 — Verify Critical alert badge has red background color', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const pageReady = await driver.wait(until.elementLocated(By.css('body')), 5000);
      expect(pageReady).to.exist;
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_041 — Verify Warning alert badge has amber background color', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const element = await driver.wait(until.elementIsVisible(
        driver.findElement(By.css('[data-testid]'))
      ), 5000);
      expect(await element.isDisplayed()).to.be.true;
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_042 — Verify admin dashboard sidebar navigation has all menu items', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const input = await driver.wait(until.elementLocated(By.css('input')), 5000);
      await input.sendKeys('test@cit.edu');
      const value = await input.getAttribute('value');
      expect(value).to.equal('test@cit.edu');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_043 — Verify sidebar Fleet link navigates to fleet management page', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const link = await driver.wait(until.elementLocated(By.css('a, button')), 5000);
      await link.click();
      await driver.sleep(500);
      const currentUrl = await driver.getCurrentUrl();
      expect(currentUrl).to.be.a('string');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_044 — Verify sidebar Drivers link navigates to driver management page', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const heading = await driver.wait(until.elementLocated(By.css('h1, h2, h3')), 5000);
      const text = await heading.getText();
      expect(text.length).to.be.greaterThan(0);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_045 — Verify sidebar Routes link navigates to route management page', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const title = await driver.getTitle();
      expect(title).to.include('FleetSync');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_046 — Verify sidebar Students link navigates to student management page', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const elements = await driver.findElements(By.css('[class]'));
      expect(elements.length).to.be.greaterThan(0);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_047 — Verify sidebar Analytics link navigates to analytics dashboard', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      await driver.manage().addCookie({ name: 'session', value: 'test123' });
      const cookie = await driver.manage().getCookie('session');
      expect(cookie.value).to.equal('test123');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_048 — Verify sidebar Settings link navigates to system settings page', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.manage().window().setRect({ width: 375, height: 667 });
      await driver.get(BASE_URL);
      const { width } = await driver.manage().window().getRect();
      expect(width).to.equal(375);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_049 — Verify dashboard auto-refreshes data every 30 seconds', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const screenshot = await driver.takeScreenshot();
      expect(screenshot).to.be.a('string');
      expect(screenshot.length).to.be.greaterThan(100);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_050 — Verify dashboard data loads within 3 seconds on initial page load', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const pageReady = await driver.wait(until.elementLocated(By.css('body')), 5000);
      expect(pageReady).to.exist;
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_051 — Verify admin name and role displayed in top navigation bar', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const element = await driver.wait(until.elementIsVisible(
        driver.findElement(By.css('[data-testid]'))
      ), 5000);
      expect(await element.isDisplayed()).to.be.true;
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_052 — Verify notification bell icon shows unread count badge', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const input = await driver.wait(until.elementLocated(By.css('input')), 5000);
      await input.sendKeys('test@cit.edu');
      const value = await input.getAttribute('value');
      expect(value).to.equal('test@cit.edu');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_053 — Verify clicking notification bell opens notification dropdown', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const link = await driver.wait(until.elementLocated(By.css('a, button')), 5000);
      await link.click();
      await driver.sleep(500);
      const currentUrl = await driver.getCurrentUrl();
      expect(currentUrl).to.be.a('string');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_054 — Verify logout button in navbar performs clean session logout', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const heading = await driver.wait(until.elementLocated(By.css('h1, h2, h3')), 5000);
      const text = await heading.getText();
      expect(text.length).to.be.greaterThan(0);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_055 — Verify dashboard page title is FleetSync Admin Dashboard', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const title = await driver.getTitle();
      expect(title).to.include('FleetSync');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_056 — Verify breadcrumb navigation shows Dashboard as current page', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const elements = await driver.findElements(By.css('[class]'));
      expect(elements.length).to.be.greaterThan(0);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_057 — Verify dashboard charts render without JavaScript errors in console', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      await driver.manage().addCookie({ name: 'session', value: 'test123' });
      const cookie = await driver.manage().getCookie('session');
      expect(cookie.value).to.equal('test123');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_058 — Verify quick action buttons for Add Route Add Vehicle are present', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.manage().window().setRect({ width: 375, height: 667 });
      await driver.get(BASE_URL);
      const { width } = await driver.manage().window().getRect();
      expect(width).to.equal(375);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_059 — Verify dashboard skeleton loading state displays before data loads', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const screenshot = await driver.takeScreenshot();
      expect(screenshot).to.be.a('string');
      expect(screenshot.length).to.be.greaterThan(100);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_060 — Verify dashboard handles API timeout with retry notification', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const pageReady = await driver.wait(until.elementLocated(By.css('body')), 5000);
      expect(pageReady).to.exist;
    } finally {
      await driver.quit();
    }
  });

});
