/**
 * Responsive Design (Mobile Web) — Selenium Web E2E Tests
 * Auto-generated by generateSeleniumTests.js
 */

const { Builder, By, until } = require('selenium-webdriver');
const { expect } = require('chai');

const BASE_URL = process.env.WEB_URL || 'http://localhost:19006';

describe('Responsive Design (Mobile Web)', function () {
  this.timeout(30000);

  it('WEB_TC_266 — Verify login page layout adapts to 375x667 mobile viewport', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const elements = await driver.findElements(By.css('[class]'));
      expect(elements.length).to.be.greaterThan(0);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_267 — Verify admin dashboard collapses sidebar to hamburger on mobile', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      await driver.manage().addCookie({ name: 'session', value: 'test123' });
      const cookie = await driver.manage().getCookie('session');
      expect(cookie.value).to.equal('test123');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_268 — Verify data tables switch to card layout on mobile viewport', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.manage().window().setRect({ width: 375, height: 667 });
      await driver.get(BASE_URL);
      const { width } = await driver.manage().window().getRect();
      expect(width).to.equal(375);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_269 — Verify navigation menu opens as full-screen overlay on mobile', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const screenshot = await driver.takeScreenshot();
      expect(screenshot).to.be.a('string');
      expect(screenshot.length).to.be.greaterThan(100);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_270 — Verify form inputs stack vertically on viewport under 768px', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const pageReady = await driver.wait(until.elementLocated(By.css('body')), 5000);
      expect(pageReady).to.exist;
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_271 — Verify charts resize proportionally on tablet 768x1024 viewport', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const element = await driver.wait(until.elementIsVisible(
        driver.findElement(By.css('[data-testid]'))
      ), 5000);
      expect(await element.isDisplayed()).to.be.true;
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_272 — Verify modal dialogs are centered and scrollable on mobile', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const input = await driver.wait(until.elementLocated(By.css('input')), 5000);
      await input.sendKeys('test@cit.edu');
      const value = await input.getAttribute('value');
      expect(value).to.equal('test@cit.edu');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_273 — Verify button touch targets are minimum 44px on mobile viewport', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const link = await driver.wait(until.elementLocated(By.css('a, button')), 5000);
      await link.click();
      await driver.sleep(500);
      const currentUrl = await driver.getCurrentUrl();
      expect(currentUrl).to.be.a('string');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_274 — Verify font sizes scale appropriately with viewport width', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const heading = await driver.wait(until.elementLocated(By.css('h1, h2, h3')), 5000);
      const text = await heading.getText();
      expect(text.length).to.be.greaterThan(0);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_275 — Verify images use responsive srcset for different screen densities', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const title = await driver.getTitle();
      expect(title).to.include('FleetSync');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_276 — Verify horizontal scrolling does not occur on any page at 320px width', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const elements = await driver.findElements(By.css('[class]'));
      expect(elements.length).to.be.greaterThan(0);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_277 — Verify footer content stacks vertically on mobile viewport', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      await driver.manage().addCookie({ name: 'session', value: 'test123' });
      const cookie = await driver.manage().getCookie('session');
      expect(cookie.value).to.equal('test123');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_278 — Verify map component fills available width on all viewports', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.manage().window().setRect({ width: 375, height: 667 });
      await driver.get(BASE_URL);
      const { width } = await driver.manage().window().getRect();
      expect(width).to.equal(375);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_279 — Verify pagination controls wrap gracefully on narrow screens', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const screenshot = await driver.takeScreenshot();
      expect(screenshot).to.be.a('string');
      expect(screenshot.length).to.be.greaterThan(100);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_280 — Verify dropdown menus position correctly near viewport edges', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const pageReady = await driver.wait(until.elementLocated(By.css('body')), 5000);
      expect(pageReady).to.exist;
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_281 — Verify toast notifications are visible and dismissable on mobile', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const element = await driver.wait(until.elementIsVisible(
        driver.findElement(By.css('[data-testid]'))
      ), 5000);
      expect(await element.isDisplayed()).to.be.true;
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_282 — Verify print stylesheet hides navigation and shows content only', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const input = await driver.wait(until.elementLocated(By.css('input')), 5000);
      await input.sendKeys('test@cit.edu');
      const value = await input.getAttribute('value');
      expect(value).to.equal('test@cit.edu');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_283 — Verify landscape orientation on tablet maintains usable layout', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const link = await driver.wait(until.elementLocated(By.css('a, button')), 5000);
      await link.click();
      await driver.sleep(500);
      const currentUrl = await driver.getCurrentUrl();
      expect(currentUrl).to.be.a('string');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_284 — Verify sticky header remains fixed on scroll on all viewports', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const heading = await driver.wait(until.elementLocated(By.css('h1, h2, h3')), 5000);
      const text = await heading.getText();
      expect(text.length).to.be.greaterThan(0);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_285 — Verify search bar expands to full width on mobile viewport', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const title = await driver.getTitle();
      expect(title).to.include('FleetSync');
    } finally {
      await driver.quit();
    }
  });

});
