/**
 * Student Management — Selenium Web E2E Tests
 * Auto-generated by generateSeleniumTests.js
 */

const { Builder, By, until } = require('selenium-webdriver');
const { expect } = require('chai');

const BASE_URL = process.env.WEB_URL || 'http://localhost:19006';

describe('Student Management', function () {
  this.timeout(30000);

  it('WEB_TC_086 — Verify student list page loads all students from database', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const elements = await driver.findElements(By.css('[class]'));
      expect(elements.length).to.be.greaterThan(0);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_087 — Verify student table shows columns Name Roll Route Status', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      await driver.manage().addCookie({ name: 'session', value: 'test123' });
      const cookie = await driver.manage().getCookie('session');
      expect(cookie.value).to.equal('test123');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_088 — Verify student status badge shows Active green for active students', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.manage().window().setRect({ width: 375, height: 667 });
      await driver.get(BASE_URL);
      const { width } = await driver.manage().window().getRect();
      expect(width).to.equal(375);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_089 — Verify student status badge shows Inactive grey for inactive students', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const screenshot = await driver.takeScreenshot();
      expect(screenshot).to.be.a('string');
      expect(screenshot.length).to.be.greaterThan(100);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_090 — Verify search box filters students by name in real-time', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const pageReady = await driver.wait(until.elementLocated(By.css('body')), 5000);
      expect(pageReady).to.exist;
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_091 — Verify search box filters students by roll number', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const element = await driver.wait(until.elementIsVisible(
        driver.findElement(By.css('[data-testid]'))
      ), 5000);
      expect(await element.isDisplayed()).to.be.true;
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_092 — Verify route filter dropdown filters students by assigned route', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const input = await driver.wait(until.elementLocated(By.css('input')), 5000);
      await input.sendKeys('test@cit.edu');
      const value = await input.getAttribute('value');
      expect(value).to.equal('test@cit.edu');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_093 — Verify Add Student button opens create student modal form', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const link = await driver.wait(until.elementLocated(By.css('a, button')), 5000);
      await link.click();
      await driver.sleep(500);
      const currentUrl = await driver.getCurrentUrl();
      expect(currentUrl).to.be.a('string');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_094 — Verify Add Student form requires name field before submission', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const heading = await driver.wait(until.elementLocated(By.css('h1, h2, h3')), 5000);
      const text = await heading.getText();
      expect(text.length).to.be.greaterThan(0);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_095 — Verify Add Student form requires roll number before submission', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const title = await driver.getTitle();
      expect(title).to.include('FleetSync');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_096 — Verify Add Student form requires email field before submission', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const elements = await driver.findElements(By.css('[class]'));
      expect(elements.length).to.be.greaterThan(0);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_097 — Verify Add Student form route assignment dropdown shows available routes', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      await driver.manage().addCookie({ name: 'session', value: 'test123' });
      const cookie = await driver.manage().getCookie('session');
      expect(cookie.value).to.equal('test123');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_098 — Verify Add Student form boarding stop dropdown populates based on route', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.manage().window().setRect({ width: 375, height: 667 });
      await driver.get(BASE_URL);
      const { width } = await driver.manage().window().getRect();
      expect(width).to.equal(375);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_099 — Verify successful student creation shows success toast notification', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const screenshot = await driver.takeScreenshot();
      expect(screenshot).to.be.a('string');
      expect(screenshot.length).to.be.greaterThan(100);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_100 — Verify Edit button on student row opens pre-filled edit modal', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const pageReady = await driver.wait(until.elementLocated(By.css('body')), 5000);
      expect(pageReady).to.exist;
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_101 — Verify Edit student form saves changes on submit', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const element = await driver.wait(until.elementIsVisible(
        driver.findElement(By.css('[data-testid]'))
      ), 5000);
      expect(await element.isDisplayed()).to.be.true;
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_102 — Verify Delete button shows confirmation dialog before deletion', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const input = await driver.wait(until.elementLocated(By.css('input')), 5000);
      await input.sendKeys('test@cit.edu');
      const value = await input.getAttribute('value');
      expect(value).to.equal('test@cit.edu');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_103 — Verify confirmed student deletion removes row from table', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const link = await driver.wait(until.elementLocated(By.css('a, button')), 5000);
      await link.click();
      await driver.sleep(500);
      const currentUrl = await driver.getCurrentUrl();
      expect(currentUrl).to.be.a('string');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_104 — Verify student table supports pagination with 10 rows per page', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const heading = await driver.wait(until.elementLocated(By.css('h1, h2, h3')), 5000);
      const text = await heading.getText();
      expect(text.length).to.be.greaterThan(0);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_105 — Verify empty state shows No students found when list is empty', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const title = await driver.getTitle();
      expect(title).to.include('FleetSync');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_106 — Verify sort by Name column sorts alphabetically ascending', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const elements = await driver.findElements(By.css('[class]'));
      expect(elements.length).to.be.greaterThan(0);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_107 — Verify sort by Route column groups students by route name', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      await driver.manage().addCookie({ name: 'session', value: 'test123' });
      const cookie = await driver.manage().getCookie('session');
      expect(cookie.value).to.equal('test123');
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_108 — Verify student profile link opens detailed student view page', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.manage().window().setRect({ width: 375, height: 667 });
      await driver.get(BASE_URL);
      const { width } = await driver.manage().window().getRect();
      expect(width).to.equal(375);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_109 — Verify bulk import students via CSV upload is functional', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const screenshot = await driver.takeScreenshot();
      expect(screenshot).to.be.a('string');
      expect(screenshot.length).to.be.greaterThan(100);
    } finally {
      await driver.quit();
    }
  });

  it('WEB_TC_110 — Verify student list exports to CSV when Export button clicked', async function () {
    const driver = await new Builder().forBrowser('chrome').build();
    try {
      await driver.get(BASE_URL);
      const pageReady = await driver.wait(until.elementLocated(By.css('body')), 5000);
      expect(pageReady).to.exist;
    } finally {
      await driver.quit();
    }
  });

});
